---
version: 2
jobs:

  build:
    docker:
      - image: circleci/golang
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get -y install shellcheck shfmt
      - run: pip install pre-commit
      - run: pre-commit install
