---
version: 2
jobs:

  build:
    docker:
      - image: circleci/golang
    steps:
      - run: go get -u mvdan.cc/sh/cmd/shfmt
      - run: sudo apt-get -y install shellcheck
      - run: |
          export PATH=$PATH:/home/circleci/.local/bin
          sudo apt-get -y install python3
          wget -O get-pip.py 'https://bootstrap.pypa.io/get-pip.py'
          python3 get-pip.py --disable-pip-version-check --no-cache-dir pip==19.1 --user
      - run: pip install pre-commit --user
      - run: pre-commit install
