---
version: 2
jobs:

  build:
    docker:
      - image: circleci/python
    steps:
      - run: |
          cd /tmp && wget https://dl.google.com/go/go1.11.linux-amd64.tar.gz
          sudo tar -xvf go1.11.linux-amd64.tar.gz
          sudo mv go /usr/local/bin
      - run: |
          echo 'export GOROOT=/usr/local/go' >> ~/.profile
          echo "export GOPATH=$(realpath $HOME/go)" >> ~/.profile
          echo 'export PATH=$GOPATH/bin:$GOROOT/bin:$PATH' >> ~/.profile
          source ~/.profile
      - run: |
          cd $(mktemp -d)
          go mod init tmp
          go get mvdan.cc/sh/cmd/shfmt
      - run: sudo apt-get -y install shellcheck
      - run: pip install pre-commit
      - run: pre-commit install
