---
version: 2
jobs:

  build:
    docker:
      - image: circleci/python
    environment:
      GOPATH: $HOME/go
    steps:
      - run: mkdir -p $GOPATH && export PATH=$PATH:$GOPATH/bin
      - run: sudo apt-get -y install golang
      - run: go get -u mvdan.cc/sh/cmd/shfmt
      - run: sudo apt-get -y install shellcheck
      - run: pip install pre-commit
      - run: pre-commit install
